# Rules Reference: https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
# Sample YAML Config: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Exclude headings
  headings: false
  # Exclude headers
  headers: false
  # Exclude tables
  tables: false
  # Stern length checking (warn only)
  stern: true

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  allow_different_nesting: true
  # Only check sibling headings
  siblings_only: true

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: 'one_or_ordered'

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: 'fenced'
